name: Cypress Framework
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run project
          start: npm start
          record: true
  
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          
  ui-chrome-tests:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Cypress run
          uses: cypress-io/github-action@v2
          with:
            start: npm start
            build: npm run project
            wait-on: "http://localhost:3000"
            record: true
            parallel: true
            browser: chrome
            headless: true

          env:
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    
    
          
        

          


